<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>528d6a62-00d0-47d7-baf6-057bc17de3f7</PollGuid>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2340.22417</VersionNumber>
        <PollSummary></PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>a1264410-ecc3-4e27-9535-5d886484486a</CreatorDeviceGuid>
        <CreatorName>SBall</CreatorName>
        <CreationDate>2006-05-31T06:56:32</CreationDate>
        <OpenPassword></OpenPassword>
        <ModifyPassword></ModifyPassword>
        <GetPersonalInfo>True</GetPersonalInfo>
        <HideQuestionNumbers>False</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>2006-06-27T16:31:43</LastEditDate>
        <LastEditGuid>ea592c78-0c79-4b42-a699-154e9445bdf0</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <DoNotUseBeforeDate>0001-01-01T00:00:00</DoNotUseBeforeDate>
        <DoNotUseAfterDate>0001-01-01T00:00:00</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <BeforePoll></BeforePoll>
        <RepeatBeforePoll>False</RepeatBeforePoll>
        <BeginMessage></BeginMessage>
        <AfterPoll></AfterPoll>
        <RepeatAfterPoll>False</RepeatAfterPoll>
        <EndMessage></EndMessage>
        <AfterAllPolls></AfterAllPolls>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the name of the mining plant?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>Coleman Mine</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Text>Creighton Mine</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>2</ID>
                    <Text>Garson Mine</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>3</ID>
                    <Text>Frood-Stobie Mine</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>4</ID>
                    <Text>North Mine</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>5</ID>
                    <Text>South Mine</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the level and workplace name?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>6</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>2</Index>
            <ID>2</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the machine operator's name?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>7</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>3</Index>
            <ID>3</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the machine number?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>8</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>4</Index>
            <ID>10</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the supervisor's name?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>27</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>5</Index>
            <ID>4</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the level of housekeeping on the deck of the machine?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>9</ID>
                    <Text>Excellent. All materials stored neatly.  No hazards</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>10</ID>
                    <Text>Good.  A few items out of place. No hazards</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>11</ID>
                    <Text>Reasonable.  Some hazards noted.</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>12</ID>
                    <Text>Poor.  Materials scattered around.  A number of hazards</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>13</ID>
                    <Text>Terrible.  Housekeeping level creating multiple hazards</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>6</Index>
            <ID>5</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the "drill rotation pressure setting range"?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>14</ID>
                    <Text>Less than 500 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>15</ID>
                    <Text>500-650 psi (within spec)</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>16</ID>
                    <Text>Greater than 650 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>7</Index>
            <ID>6</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the "drill impact pressure setting range"?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>17</ID>
                    <Text>Less than 1,700 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>18</ID>
                    <Text>1,700-1,900 psi (within spec)</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>19</ID>
                    <Text>Greater than 1,900 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>8</Index>
            <ID>7</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the "drill impact low pressure collaring"?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>20</ID>
                    <Text>Less than 1,000 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>21</ID>
                    <Text>Approximately 1,000 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>22</ID>
                    <Text>Greater than 1,000 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>9</Index>
            <ID>8</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the "bolt rotation pressure?"</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>23</ID>
                    <Text>Less than 1,500 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>24</ID>
                    <Text>Approximately 1,500 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>25</ID>
                    <Text>Greater than 1,500 psi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>10</Index>
            <ID>11</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the "bolt free-spin rotation speed"?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>28</ID>
                    <Text>Less than 300 rpm</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>29</ID>
                    <Text>Approximately 300 rpm</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>30</ID>
                    <Text>Greater than 300 rpm</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>11</Index>
            <ID>12</ID>
            <Mandatory>False</Mandatory>
            <Text>What are the typical hazards associated with incorrect machine settings?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>MultipleChoice</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>31</ID>
                    <Text>Improper mixing of resin cartridges (rebar &amp; cone bolts)</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>32</ID>
                    <Text>Over-torquing bolts</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>33</ID>
                    <Text>Insertion speed hazards to operators</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>12</Index>
            <ID>13</ID>
            <Mandatory>False</Mandatory>
            <Text>What improper installations are seen at this site?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>MultipleChoice</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>34</ID>
                    <Text>None</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>35</ID>
                    <Text>Resin not coming out of hole (rebar, cone)</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>36</ID>
                    <Text>Over-torqued plates on mechanical bolts</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>37</ID>
                    <Text>Other</Text>
                    <MoreText>Please specify</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>13</Index>
            <ID>14</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the operator's knowledge level of the hazards associated with incorrect pressure settings?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>MultipleChoice</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>38</ID>
                    <Text>Very good.  Knowledge of required pressures is thorough.</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>39</ID>
                    <Text>Good.  Realized that incorrect pressures can compromise ground support</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>40</ID>
                    <Text>Fair.  Could remember something in training about this</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>41</ID>
                    <Text>Poor.  Had no idea of the consequences that could result from incorrect settings</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>14</Index>
            <ID>17</ID>
            <Mandatory>False</Mandatory>
            <Text>Test Question inserted by RW</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>48</ID>
                    <Text>Very good.  Knowledge of required pressures is thorough.</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>47</ID>
                    <Text>Good.  Realized that incorrect pressures can compromise ground support</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>49</ID>
                    <Text>Fair.  Could remember something in training about this</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>50</ID>
                    <Text>Poor.  Had no idea of the consequences that could result from incorrect settings</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>15</Index>
            <ID>15</ID>
            <Mandatory>False</Mandatory>
            <Text>What did information did the operator receive during training?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>MultipleChoice</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>42</ID>
                    <Text>Lots.  A good discussion of pressure settings and affects on ground support occurred</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>43</ID>
                    <Text>Reasonable.  The training instructor did cover some of these items</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>44</ID>
                    <Text>Poor.  No information was passed on during training regarding incorrect settings</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>16</Index>
            <ID>16</ID>
            <Mandatory>False</Mandatory>
            <Text>Other comments</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>46</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
    </Respondents>
    <PollingInfo>
        <PollsterName></PollsterName>
        <ProductID>Lite</ProductID>
        <VersionNumber></VersionNumber>
        <StartPolling>0001-01-01T00:00:00</StartPolling>
        <FinishPolling>0001-01-01T00:00:00</FinishPolling>
        <Guid></Guid>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <EditCapturedData>False</EditCapturedData>
        <ViewPrevCapturedData>False</ViewPrevCapturedData>
        <ShowRunningStats>False</ShowRunningStats>
        <ShowEndStats>False</ShowEndStats>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
