<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>b9cea90e-892c-4e5a-a371-31eb7ce90a83</PollGuid>
        <Revision>0</Revision>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2139.29449</VersionNumber>
        <PollSummary>The senior Yahoo was Geoff Ralston, chief product officer. After some preliminary fencing (are services products? yes) Geoff looked for feedback about Yahoo's aggressive RSS stance. I gently walked him from RSS to attention, then dropped the bomb: Now that everything is about attention, we're on the move to the Gesture Economy.</PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>d8adbc9c-48c0-4285-88ce-055a4495a2d6</CreatorDeviceGuid>
        <CreatorName>RWerner</CreatorName>
        <CreationDate>2005-11-09T16:21:43</CreationDate>
        <GetPersonalInfo>False</GetPersonalInfo>
        <HideQuestionNumbers>False</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>2006-09-06T17:39:23</LastEditDate>
        <LastEditGuid>859ecabf-357e-4000-8fe8-e1ce9ca46ec5</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <ExportEnabled>False</ExportEnabled>
        <LastCompact>0001-01-01T00:00:00</LastCompact>
        <DoNotUseBeforeDate>0001-01-01T00:00:00</DoNotUseBeforeDate>
        <DoNotUseAfterDate>0001-01-01T00:00:00</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <RepeatBeforePoll>False</RepeatBeforePoll>
        <RepeatAfterPoll>False</RepeatAfterPoll>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <Text>Sample Question #1</Text>
            <AnswerFormat>Range</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>Choice A</Text>
                    <MoreText>1</MoreText>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Text>Choice B</Text>
                    <MoreText>2</MoreText>
                    <ExtraInfo>True</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>5</ID>
                    <Text>Choice C</Text>
                    <MoreText>3</MoreText>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>6</ID>
                    <Text>Choice D</Text>
                    <MoreText>4</MoreText>
                    <ExtraInfo>True</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>7</ID>
                    <Text>Choice E</Text>
                    <MoreText>5</MoreText>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>8</ID>
                    <Text>Choice F</Text>
                    <MoreText>6</MoreText>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>2</ID>
            <Mandatory>False</Mandatory>
            <Text>How many seats do you think each party will get?</Text>
            <AnswerFormat>MultipleBoxes</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>9</ID>
                    <Text>Conservatives</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>10</ID>
                    <Text>Liberals</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>11</ID>
                    <Text>NDP</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>12</ID>
                    <Text>Bloc Quebecois</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>2</Index>
            <ID>3</ID>
            <Mandatory>False</Mandatory>
            <Text>Please rank the following issues in order of importance to you (1 being highest) :</Text>
            <AnswerFormat>MultipleBoxes</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>13</ID>
                    <Text>Education</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>14</ID>
                    <Text>Lowering the Debt</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>15</ID>
                    <Text>Health Care</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>16</ID>
                    <Text>Military</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>3</Index>
            <ID>4</ID>
            <Mandatory>False</Mandatory>
            <Text>How do you think Stephen Harper should handle the terrorist threat?</Text>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>17</ID>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>4</Index>
            <ID>5</ID>
            <Mandatory>False</Mandatory>
            <Text>What's the maximum percentage of the provincial budget that should be devoted to health care?</Text>
            <AnswerFormat>Spinner</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>18</ID>
                    <Text>0</Text>
                    <MoreText>100</MoreText>
                    <MoreText2>1</MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>5</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <Text>What choice do you like best?</Text>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>Choice A</Text>
                    <MoreText>More info please</MoreText>
                    <ExtraInfo>True</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Text>Choice B</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>5</ID>
                    <Text>Choice C</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>6</ID>
                    <Text>Choice D</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>7</ID>
                    <Text>Choice E</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>8</ID>
                    <Text>Choice F</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>6</Index>
                    <ID>2</ID>
                    <Text>Other</Text>
                    <MoreText>Please specify</MoreText>
                    <ExtraInfo>True</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
    </Respondents>
    <PollingInfo>
        <ProductID>Lite</ProductID>
        <StartPolling>0001-01-01T00:00:00</StartPolling>
        <FinishPolling>0001-01-01T00:00:00</FinishPolling>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <ReviewData>True</ReviewData>
        <CanAbortRecord>True</CanAbortRecord>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
