<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>b9cea90e-892c-4e5a-a371-31eb7ce90a83</PollGuid>
        <Revision>0</Revision>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2139.29449</VersionNumber>
        <PollSummary>Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, Who am I to be brilliant, gorgeous, talented, fabulous? Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won't feel insecure around you. We are all meant to shine, as children do. We were born to make manifest the glory of God that is within us. It is not just in some of us; it is in everyone. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others.</PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>d8adbc9c-48c0-4285-88ce-055a4495a2d6</CreatorDeviceGuid>
        <CreatorName>RWerner</CreatorName>
        <CreationDate>2005-11-09T16:21:43</CreationDate>
        <GetPersonalInfo>False</GetPersonalInfo>
        <HideQuestionNumbers>False</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>2006-09-06T22:40:47</LastEditDate>
        <LastEditGuid>8ab756f7-1902-4ee5-ae33-6a905ca99881</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <ExportEnabled>False</ExportEnabled>
        <LastCompact>0001-01-01T00:00:00</LastCompact>
        <DoNotUseBeforeDate>0001-01-01T00:00:00</DoNotUseBeforeDate>
        <DoNotUseAfterDate>0001-01-01T00:00:00</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <BeforePoll>Here are some sample Instructions to populate this text box.</BeforePoll>
        <RepeatBeforePoll>False</RepeatBeforePoll>
        <AfterPoll>Here is an amperand &amp; and here is another one &amp;</AfterPoll>
        <RepeatAfterPoll>False</RepeatAfterPoll>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <Text>Sample Question #1</Text>
            <AnswerFormat>MultipleBoxes</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>Choice A</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Text>Choice B</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>2</ID>
                    <Text>Choice C</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>3</ID>
                    <Text>Choice D</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>10</ID>
                    <Text>Choice E</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>11</ID>
                    <Text>Choice F</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <AnswerFormat>Spinner</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>4</ID>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>2</Index>
            <ID>2</ID>
            <Mandatory>False</Mandatory>
            <AnswerFormat>DropList</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>5</ID>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>3</Index>
            <ID>3</ID>
            <Mandatory>False</Mandatory>
            <AnswerFormat>MultipleChoice</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>6</ID>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>4</Index>
            <ID>4</ID>
            <Mandatory>False</Mandatory>
            <AnswerFormat>Range</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>7</ID>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>5</Index>
            <ID>5</ID>
            <Mandatory>False</Mandatory>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>8</ID>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
    </Respondents>
    <PollingInfo>
        <ProductID>Lite</ProductID>
        <StartPolling>0001-01-01T00:00:00</StartPolling>
        <FinishPolling>0001-01-01T00:00:00</FinishPolling>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <ReviewData>True</ReviewData>
        <CanAbortRecord>True</CanAbortRecord>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
