<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>98e0e5c1-7fdf-466c-a684-e9cb15886894</PollGuid>
        <Revision>0</Revision>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2178.32078</VersionNumber>
        <PollSummary></PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>d8adbc9c-48c0-4285-88ce-055a4495a2d6</CreatorDeviceGuid>
        <CreatorName>RWerner</CreatorName>
        <CreationDate>2005-12-18T17:49:28</CreationDate>
        <GetPersonalInfo>True</GetPersonalInfo>
        <HideQuestionNumbers>False</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>2006-09-06T22:41:07</LastEditDate>
        <LastEditGuid>735f1eae-c6e4-4a79-9599-cd283c509c9b</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <ExportEnabled>False</ExportEnabled>
        <LastCompact>0001-01-01T00:00:00</LastCompact>
        <DoNotUseBeforeDate>0001-01-01T00:00:00</DoNotUseBeforeDate>
        <DoNotUseAfterDate>0001-01-01T00:00:00</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <RepeatBeforePoll>False</RepeatBeforePoll>
        <RepeatAfterPoll>False</RepeatAfterPoll>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <AnswerFormat>Spinner</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>1</Text>
                    <MoreText>10</MoreText>
                    <MoreText2>1</MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <AnswerFormat>Spinner</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>1</ID>
                    <Text>0</Text>
                    <MoreText>30</MoreText>
                    <MoreText2>4</MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
    </Respondents>
    <PollingInfo>
        <PollsterName></PollsterName>
        <ProductID>Lite</ProductID>
        <VersionNumber></VersionNumber>
        <StartPolling>0001-01-01T00:00:00</StartPolling>
        <FinishPolling>0001-01-01T00:00:00</FinishPolling>
        <Guid></Guid>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <ReviewData>False</ReviewData>
        <CanAbortRecord>True</CanAbortRecord>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
