<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>fca4b2ce-13a1-4692-aa69-3ee899e440e2</PollGuid>
        <Revision>0</Revision>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2165.32601</VersionNumber>
        <PollSummary>This is a sample political poll using questions that are directly applicable to the January 23, 2006 Canadian Federal Election.</PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>d8adbc9c-48c0-4285-88ce-055a4495a2d6</CreatorDeviceGuid>
        <CreatorName>RWerner</CreatorName>
        <CreationDate>2005-12-05T18:07:04</CreationDate>
        <GetPersonalInfo>False</GetPersonalInfo>
        <HideQuestionNumbers>True</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>2006-09-06T22:41:25</LastEditDate>
        <LastEditGuid>f24afdad-59a3-4e59-a980-fc565343a3ba</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <ExportEnabled>False</ExportEnabled>
        <LastCompact>0001-01-01T00:00:00</LastCompact>
        <DoNotUseBeforeDate>0001-01-01T00:00:00</DoNotUseBeforeDate>
        <DoNotUseAfterDate>0001-01-01T00:00:00</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <BeforePoll>When talking with each respondent, please be sure to not be biased in any way, including tone, rolling of your eyes, etc.  From the way you ask the questions, the person should not be given any clue as to your own political views.</BeforePoll>
        <RepeatBeforePoll>True</RepeatBeforePoll>
        <BeginMessage>Thank you for taking the time to answer our polling questions today.  The entire process should not take more than 2 minutes.  I will read out each question slowly and carefully.  I can repeat any question you did not hear properly but I cannot answer any other questions related to the poll.</BeginMessage>
        <RepeatAfterPoll>False</RepeatAfterPoll>
        <EndMessage>Thank you for taking the time to answer the questions I've asked you today.  It is much appreciated!</EndMessage>
        <AfterAllPolls>Please be sure to sync your mobile device before you finish your shift.</AfterAllPolls>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>6</ID>
            <Mandatory>False</Mandatory>
            <Text>On which date will the the upcoming federal election be?</Text>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>15</ID>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>7</ID>
            <Mandatory>False</Mandatory>
            <Text>Do you plan to vote?</Text>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>16</ID>
                    <Text>Yes</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>17</ID>
                    <Text>No</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>18</ID>
                    <Text>Not sure</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>2</Index>
            <ID>8</ID>
            <Mandatory>False</Mandatory>
            <Text>Which of the following are important issues for you?</Text>
            <AnswerFormat>MultipleChoice</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>26</ID>
                    <Text>Economy &amp; Taxes</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>27</ID>
                    <Text>Health Care</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>28</ID>
                    <Text>Crime &amp; Justice</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>29</ID>
                    <Text>Education</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>31</ID>
                    <Text>Military</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>30</ID>
                    <Text>Government Corruption</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>3</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <Text>Who do you believe will win the next federal election in Canada?</Text>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>Liberals</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Text>Conservatives</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>2</ID>
                    <Text>NDP</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>3</ID>
                    <Text>Bloc Quebecois</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>4</ID>
                    <Text>Other</Text>
                    <MoreText>Please specify</MoreText>
                    <ExtraInfo>True</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>4</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <Text>Do you think this party will win a majority or minority government?</Text>
            <AnswerFormat>List</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>5</ID>
                    <Text>Majority</Text>
                    <MoreText>1</MoreText>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>6</ID>
                    <Text>Minority</Text>
                    <MoreText>2</MoreText>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>5</Index>
            <ID>2</ID>
            <Mandatory>False</Mandatory>
            <Text>Of 308 possible seats, how many will each party get?</Text>
            <AnswerFormat>MultipleBoxes</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>7</ID>
                    <Text>Liberals</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>19</ID>
                    <Text>Conservatives</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>21</ID>
                    <Text>NDP</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>22</ID>
                    <Text>Bloc Quebecois</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>23</ID>
                    <Text>Green Party</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>25</ID>
                    <Text>Other</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>6</Index>
            <ID>4</ID>
            <Mandatory>False</Mandatory>
            <Text>If another minority government is elected, how long do you think it'll be before it is defeated?</Text>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>9</ID>
                    <Text>Less than 6 months</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>10</ID>
                    <Text>6 to 12 months</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>11</ID>
                    <Text>12 to 18 months</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>12</ID>
                    <Text>18 to 24 months</Text>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>13</ID>
                    <Text>More than 24 months</Text>
                    <MoreText>Specify, if you want</MoreText>
                    <ExtraInfo>False</ExtraInfo>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
    </Respondents>
    <PollingInfo>
        <ProductID>Lite</ProductID>
        <StartPolling>0001-01-01T00:00:00</StartPolling>
        <FinishPolling>0001-01-01T00:00:00</FinishPolling>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <ReviewData>True</ReviewData>
        <CanAbortRecord>True</CanAbortRecord>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
