<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>b9cea90e-892c-4e5a-a371-31eb7ce90a83</PollGuid>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2139.29449</VersionNumber>
        <PollSummary></PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>d8adbc9c-48c0-4285-88ce-055a4495a2d6</CreatorDeviceGuid>
        <CreatorName>RWerner</CreatorName>
        <CreationDate>11/9/2005 4:21:43 PM</CreationDate>
        <OpenPassword></OpenPassword>
        <ModifyPassword></ModifyPassword>
        <GetPersonalInfo>False</GetPersonalInfo>
        <HideQuestionNumbers>False</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>4/5/2006 10:14:21 PM</LastEditDate>
        <LastEditGuid>4332d718-de5a-4ea4-8607-0f4832de4791</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <DoNotUseBeforeDate>1/1/0001 12:00:00 AM</DoNotUseBeforeDate>
        <DoNotUseAfterDate>1/1/0001 12:00:00 AM</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <BeforePoll>Here are some sample Instructions to populate this text box.</BeforePoll>
        <RepeatBeforePoll>False</RepeatBeforePoll>
        <BeginMessage></BeginMessage>
        <AfterPoll>Here is an amperand &amp; and here is another one &amp;</AfterPoll>
        <RepeatAfterPoll>False</RepeatAfterPoll>
        <EndMessage></EndMessage>
        <AfterAllPolls></AfterAllPolls>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <Text>Sample Question #1</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>MultipleChoice</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>Choice A</Text>
                    <MoreText>Short Intro</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Text>Choice B</Text>
                    <MoreText>A bit longer intro</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>2</ID>
                    <Text>Choice C</Text>
                    <MoreText>You can add more info here:</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>3</ID>
                    <Text>Choice D</Text>
                    <MoreText>And here's an even longer intro than before</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>10</ID>
                    <Text>Choice E</Text>
                    <MoreText>Now for something absolutely ridiculous that should take up many lines on the Pocket PC</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>11</ID>
                    <Text>Choice F</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <Text>On a scale of 1 - 100, how you would rate the ride you just took on this roller coaster? (100 being best)</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Spinner</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>4</ID>
                    <Text>1</Text>
                    <MoreText>100</MoreText>
                    <MoreText2>1</MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>2</Index>
            <ID>2</ID>
            <Mandatory>False</Mandatory>
            <Text>What's your favourite soft drink?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>DropList</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>5</ID>
                    <Text>Coke</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>12</ID>
                    <Text>Pepsi</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>22</ID>
                    <Text>7-Up</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>23</ID>
                    <Text>Canada Dry</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>13</ID>
                    <Text>Other</Text>
                    <MoreText>Please specify the brand</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>3</Index>
            <ID>3</ID>
            <Mandatory>False</Mandatory>
            <Text>On a scale of 1 - 10, how would you rate each movie? (10 being the best)</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>MultipleBoxes</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>6</ID>
                    <Text>Crash</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>14</ID>
                    <Text>Star Wars</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>15</ID>
                    <Text>The Pink Panther</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>16</ID>
                    <Text>Intolerable Cruelty</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>21</ID>
                    <Text>Finding Nemo</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>4</Index>
            <ID>4</ID>
            <Mandatory>False</Mandatory>
            <Text>How much did you like the product you just tasted?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Range</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>7</ID>
                    <Text>Loved it</Text>
                    <MoreText>5</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>17</ID>
                    <Text>Liked it</Text>
                    <MoreText>4</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>18</ID>
                    <Text>Take it or leave it</Text>
                    <MoreText>3</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>19</ID>
                    <Text>Disliked it</Text>
                    <MoreText>2</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>20</ID>
                    <Text>Hated it</Text>
                    <MoreText>1</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>5</Index>
            <ID>5</ID>
            <Mandatory>False</Mandatory>
            <Text>Are there any other comments you'd like to add?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>8</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
    </Respondents>
    <PollingInfo>
        <PollsterName></PollsterName>
        <ProductID>Lite</ProductID>
        <VersionNumber></VersionNumber>
        <StartPolling>1/1/0001 12:00:00 AM</StartPolling>
        <FinishPolling>1/1/0001 12:00:00 AM</FinishPolling>
        <Guid></Guid>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <EditCapturedData>False</EditCapturedData>
        <ViewPrevCapturedData>False</ViewPrevCapturedData>
        <ShowRunningStats>False</ShowRunningStats>
        <ShowEndStats>False</ShowEndStats>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
