<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>b9cea90e-892c-4e5a-a371-31eb7ce90a83</PollGuid>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2139.29449</VersionNumber>
        <PollSummary></PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>d8adbc9c-48c0-4285-88ce-055a4495a2d6</CreatorDeviceGuid>
        <CreatorName>RWerner</CreatorName>
        <CreationDate>11/9/2005 4:21:43 PM</CreationDate>
        <OpenPassword></OpenPassword>
        <ModifyPassword></ModifyPassword>
        <GetPersonalInfo>False</GetPersonalInfo>
        <HideQuestionNumbers>False</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>12/8/2005 7:19:07 PM</LastEditDate>
        <LastEditGuid>3f1c86d2-6850-418a-8673-9c3ce7cb0ee5</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <DoNotUseBeforeDate>1/1/0001 12:00:00 AM</DoNotUseBeforeDate>
        <DoNotUseAfterDate>1/1/0001 12:00:00 AM</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <BeforePoll>Here are some sample Instructions to populate this text box.</BeforePoll>
        <RepeatBeforePoll>False</RepeatBeforePoll>
        <BeginMessage></BeginMessage>
        <AfterPoll></AfterPoll>
        <RepeatAfterPoll>False</RepeatAfterPoll>
        <EndMessage></EndMessage>
        <AfterAllPolls></AfterAllPolls>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <Text>Sample Question #1</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>MultipleBoxes</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text>Choice A</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Text>Choice B</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>2</ID>
                    <Text>Choice C</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>3</ID>
                    <Text>Choice D</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <Text></Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>4</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>2</Index>
            <ID>2</ID>
            <Mandatory>False</Mandatory>
            <Text></Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>5</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>3</Index>
            <ID>3</ID>
            <Mandatory>False</Mandatory>
            <Text></Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>6</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>4</Index>
            <ID>4</ID>
            <Mandatory>False</Mandatory>
            <Text></Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>7</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>5</Index>
            <ID>5</ID>
            <Mandatory>False</Mandatory>
            <Text></Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>8</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
        <Respondent>
            <Index>0</Index>
            <ID>0</ID>
            <PollsterName>rwerner</PollsterName>
            <Guid>95ac5a26-22eb-4a78-88de-5ea67e784b17</Guid>
            <TimeCaptured>3/17/2006 8:21:29 PM</TimeCaptured>
            <GPS></GPS>
            <FirstName>Deepak</FirstName>
            <LastName>Chopra</LastName>
            <Address></Address>
            <City></City>
            <StateProv></StateProv>
            <PostalCode></PostalCode>
            <AreaCode></AreaCode>
            <TelNum></TelNum>
            <TelNum2></TelNum2>
            <Sex>Unspecified</Sex>
            <Age>0</Age>
            <Image>#TBD#</Image>
            <Responses>
                <Response>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Guid>9b17225f-ea3e-41ab-b51b-d7740bb5cc92</Guid>
                    <TimeCaptured>3/17/2006 8:22:39 PM</TimeCaptured>
                    <QuestionID>0</QuestionID>
                    <AnswerID>0</AnswerID>
                    <LastModified>3/17/2006 8:22:39 PM</LastModified>
                    <ExtraText>0~x</ExtraText>
                    <Authentication></Authentication>
                </Response>
                <Response>
                    <Index>1</Index>
                    <ID>1</ID>
                    <Guid></Guid>
                    <TimeCaptured>1/1/0001 12:00:00 AM</TimeCaptured>
                    <QuestionID>1</QuestionID>
                    <AnswerID></AnswerID>
                    <LastModified>1/1/0001 12:00:00 AM</LastModified>
                    <ExtraText></ExtraText>
                    <Authentication></Authentication>
                </Response>
                <Response>
                    <Index>2</Index>
                    <ID>2</ID>
                    <Guid></Guid>
                    <TimeCaptured>1/1/0001 12:00:00 AM</TimeCaptured>
                    <QuestionID>2</QuestionID>
                    <AnswerID></AnswerID>
                    <LastModified>1/1/0001 12:00:00 AM</LastModified>
                    <ExtraText></ExtraText>
                    <Authentication></Authentication>
                </Response>
                <Response>
                    <Index>3</Index>
                    <ID>3</ID>
                    <Guid></Guid>
                    <TimeCaptured>1/1/0001 12:00:00 AM</TimeCaptured>
                    <QuestionID>3</QuestionID>
                    <AnswerID></AnswerID>
                    <LastModified>1/1/0001 12:00:00 AM</LastModified>
                    <ExtraText></ExtraText>
                    <Authentication></Authentication>
                </Response>
                <Response>
                    <Index>4</Index>
                    <ID>4</ID>
                    <Guid></Guid>
                    <TimeCaptured>1/1/0001 12:00:00 AM</TimeCaptured>
                    <QuestionID>4</QuestionID>
                    <AnswerID></AnswerID>
                    <LastModified>1/1/0001 12:00:00 AM</LastModified>
                    <ExtraText></ExtraText>
                    <Authentication></Authentication>
                </Response>
                <Response>
                    <Index>5</Index>
                    <ID>5</ID>
                    <Guid></Guid>
                    <TimeCaptured>1/1/0001 12:00:00 AM</TimeCaptured>
                    <QuestionID>5</QuestionID>
                    <AnswerID></AnswerID>
                    <LastModified>1/1/0001 12:00:00 AM</LastModified>
                    <ExtraText></ExtraText>
                    <Authentication></Authentication>
                </Response>
            </Responses>
        </Respondent>
    </Respondents>
    <PollingInfo>
        <PollsterName>rwerner</PollsterName>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2267.28252</VersionNumber>
        <StartPolling>3/17/2006 8:21:29 PM</StartPolling>
        <FinishPolling>3/17/2006 8:23:22 PM</FinishPolling>
        <Guid>8ae185e8-7b6c-4ccb-b011-01d53a70cb26</Guid>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <EditCapturedData>False</EditCapturedData>
        <ViewPrevCapturedData>False</ViewPrevCapturedData>
        <ShowRunningStats>False</ShowRunningStats>
        <ShowEndStats>False</ShowEndStats>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
