<?xml version="1.0"?>
<Poll>
    <CreationInfo>
        <PollGuid>24641af2-2eae-42d0-ab60-3bee9a06f7b7</PollGuid>
        <Revision>0</Revision>
        <PollType>Standard</PollType>
        <ProductID>Plus</ProductID>
        <VersionNumber>1.0.2410.38262</VersionNumber>
        <PollSummary></PollSummary>
        <CreatorDeviceType>Windows</CreatorDeviceType>
        <CreatorDeviceGuid>e2b00fb1-3aaa-4a91-b7ff-f9644fa80b47</CreatorDeviceGuid>
        <CreatorName>RWerner</CreatorName>
        <CreationDate>2006-08-09T11:20:52</CreationDate>
        <OpenPassword></OpenPassword>
        <ModifyPassword></ModifyPassword>
        <GetPersonalInfo>True</GetPersonalInfo>
        <HideQuestionNumbers>False</HideQuestionNumbers>
        <LastEditedBy>RWerner</LastEditedBy>
        <LastEditDate>2006-08-09T11:46:48</LastEditDate>
        <LastEditGuid>ecac4b7e-0db8-4ee4-8240-a5b9ece7e0f0</LastEditGuid>
        <PurgeDuration>0</PurgeDuration>
        <ExportEnabled>False</ExportEnabled>
        <ExportFilename></ExportFilename>
        <LastCompact>0001-01-01T00:00:00</LastCompact>
        <DoNotUseBeforeDate>0001-01-01T00:00:00</DoNotUseBeforeDate>
        <DoNotUseAfterDate>0001-01-01T00:00:00</DoNotUseAfterDate>
    </CreationInfo>
    <Instructions>
        <BeforePoll></BeforePoll>
        <RepeatBeforePoll>False</RepeatBeforePoll>
        <BeginMessage></BeginMessage>
        <AfterPoll></AfterPoll>
        <RepeatAfterPoll>False</RepeatAfterPoll>
        <EndMessage></EndMessage>
        <AfterAllPolls></AfterAllPolls>
    </Instructions>
    <Questions>
        <Question>
            <Index>0</Index>
            <ID>0</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the one new feature you would use that you most want Virtual Tourist to add? (Specify only 1 feature)</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>0</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>1</Index>
            <ID>1</ID>
            <Mandatory>False</Mandatory>
            <Text>What is the one new feature for researching a trip that you most want Virtual Tourist to add? (Specify only 1 feature)</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>1</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>2</Index>
            <ID>2</ID>
            <Mandatory>False</Mandatory>
            <Text>How did you originally find the Virtual Tourist website?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>2</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>3</Index>
            <ID>3</ID>
            <Mandatory>False</Mandatory>
            <Text>Who's the coolest VT member that you've met?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>3</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>4</Index>
            <ID>4</ID>
            <Mandatory>False</Mandatory>
            <Text>Where is your dream destination?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>4</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>5</Index>
            <ID>5</ID>
            <Mandatory>False</Mandatory>
            <Text>How many trips a year do you take for business?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>5</ID>
                    <Text>0</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>6</ID>
                    <Text>1</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>7</ID>
                    <Text>2</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>8</ID>
                    <Text>3</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>9</ID>
                    <Text>4</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>10</ID>
                    <Text>5</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>6</Index>
                    <ID>11</ID>
                    <Text>More than 5</Text>
                    <MoreText>Please specify</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>6</Index>
            <ID>6</ID>
            <Mandatory>False</Mandatory>
            <Text>How many trips a year do you take for pleasure?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>12</ID>
                    <Text>0</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>13</ID>
                    <Text>1</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>14</ID>
                    <Text>2</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>15</ID>
                    <Text>3</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>16</ID>
                    <Text>4</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>17</ID>
                    <Text>5</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>6</Index>
                    <ID>18</ID>
                    <Text>More than 5</Text>
                    <MoreText>Please specify</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>7</Index>
            <ID>7</ID>
            <Mandatory>False</Mandatory>
            <Text>How many hours a day do you spend logged into VT?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>19</ID>
                    <Text>0 - 1</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>20</ID>
                    <Text>1 - 3</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>21</ID>
                    <Text>3 - 6</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>22</ID>
                    <Text>6 - 12</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>23</ID>
                    <Text>12+</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>8</Index>
            <ID>8</ID>
            <Mandatory>False</Mandatory>
            <Text>What is your favourite part of the site?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Standard</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>24</ID>
                    <Text>Destination Travelguides</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>25</ID>
                    <Text>Reading/Writing Tips</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>26</ID>
                    <Text>Member Location Intros/Travelogues</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>27</ID>
                    <Text>Member Homepages/Personal Albums</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>28</ID>
                    <Text>Forums</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>32</ID>
                    <Text>Deals</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>6</Index>
                    <ID>33</ID>
                    <Text>Meetings</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>7</Index>
                    <ID>34</ID>
                    <Text>VTMail</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>8</Index>
                    <ID>35</ID>
                    <Text>Commenting/Rating and Getting Comments/Ratings</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>9</Index>
                    <ID>36</ID>
                    <Text>Other</Text>
                    <MoreText>Please specify</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>9</Index>
            <ID>12</ID>
            <Mandatory>False</Mandatory>
            <Text>Out of the Top 10 VT Locations on the front page, which is your favourite?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Freeform</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>37</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>10</Index>
            <ID>13</ID>
            <Mandatory>False</Mandatory>
            <Text>How many of the Top 10 VT Locations on the front page have you visited?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>Spinner</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>38</ID>
                    <Text>0</Text>
                    <MoreText>10</MoreText>
                    <MoreText2>1</MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>40</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>41</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>42</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>43</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>44</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>6</Index>
                    <ID>45</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>7</Index>
                    <ID>46</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>8</Index>
                    <ID>47</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>9</Index>
                    <ID>48</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>10</Index>
                    <ID>49</ID>
                    <Text></Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
        <Question>
            <Index>11</Index>
            <ID>14</ID>
            <Mandatory>False</Mandatory>
            <Text>How many countries have you been to in your life?</Text>
            <Image>#TBD#</Image>
            <Notes></Notes>
            <AnswerFormat>List</AnswerFormat>
            <Choices>
                <Choice>
                    <Index>0</Index>
                    <ID>39</ID>
                    <Text>1</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>1</Index>
                    <ID>50</ID>
                    <Text>2</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>2</Index>
                    <ID>51</ID>
                    <Text>3</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>3</Index>
                    <ID>52</ID>
                    <Text>4</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>4</Index>
                    <ID>53</ID>
                    <Text>5</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>5</Index>
                    <ID>54</ID>
                    <Text>6 - 10</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>6</Index>
                    <ID>55</ID>
                    <Text>11 - 20</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>7</Index>
                    <ID>56</ID>
                    <Text>21 - 40</Text>
                    <MoreText></MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>False</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
                <Choice>
                    <Index>8</Index>
                    <ID>57</ID>
                    <Text>More than 40</Text>
                    <MoreText>Please specify</MoreText>
                    <MoreText2></MoreText2>
                    <ExtraInfo>True</ExtraInfo>
                    <Image>#TBD#</Image>
                    <URL></URL>
                    <CorrectAnswer>False</CorrectAnswer>
                    <GotoQuestionID>0</GotoQuestionID>
                    <Multimedia></Multimedia>
                    <ShowMultimediaNow>False</ShowMultimediaNow>
                </Choice>
            </Choices>
        </Question>
    </Questions>
    <Respondents>
    </Respondents>
    <PollingInfo>
        <PollsterName></PollsterName>
        <ProductID>Lite</ProductID>
        <VersionNumber></VersionNumber>
        <StartPolling>0001-01-01T00:00:00</StartPolling>
        <FinishPolling>0001-01-01T00:00:00</FinishPolling>
        <Guid></Guid>
    </PollingInfo>
    <PollsterPrivileges>
        <ModifyPoll>False</ModifyPoll>
        <EditCapturedData>False</EditCapturedData>
        <ViewPrevCapturedData>False</ViewPrevCapturedData>
        <ShowRunningStats>False</ShowRunningStats>
        <ShowEndStats>False</ShowEndStats>
        <CanPrint>False</CanPrint>
        <AuthenticateRespondentInfo>False</AuthenticateRespondentInfo>
        <AuthenticateResponses>False</AuthenticateResponses>
    </PollsterPrivileges>
</Poll>
